language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - python setup.py -q install
  - pip install pylint yapf
script:
  - python setup.py test
  - pylint comment_parser
  - yapf -drp --style=yapf .
